/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  // But you can create a sidebar manually
  tutorialSidebar: [
    // 'intro',
    // {
    //   type: 'category',
    //   label: 'Tutorial',
    //   items: [
    //     {type: 'autogenerated', dirName: 'tutorial-basics'}
    //   ],
    // },
    // {
    //   type: 'category',
    //   label: 'Tutorial',
    //   items: ['index'],
    // },
  ],
  gobyexample: [
    {
      type: 'autogenerated',
      dirName: 'gobyexample', // Generate sidebar slice from docs/api
    },
  ],
  gogist: [
    {
      type: 'autogenerated',
      dirName: 'gogist', // Generate sidebar slice from docs/api
    },
  ],
  gonav: [
    {
      type: 'autogenerated',
      dirName: 'gonav', // Generate sidebar slice from docs/api
    },
  ],
  mygist: [
    {
      type: 'autogenerated',
      dirName: 'mygist', // Generate sidebar slice from docs/api
    },
  ],
  mynav: [
    {
      type: 'autogenerated',
      dirName: 'mynav', // Generate sidebar slice from docs/api
    },
  ],
};

module.exports = sidebars;
